export const FETCH_CATEGORIES = 'FETCH_CATEGORIES';
export const FETCH_CATEGORIES_SUCCESS = 'FETCH_CATEGORIES_SUCCESS';

export const CREATE_CATEGORIES = 'CREATE_CATEGORIES';
export const CREATE_CATEGORY_SUCCESS = 'CREATE_CATEGORY_SUCCESS';

export const FETCH_SELECTED_CATEGORY =  'FETCH_SELECTED_CATEGORY';
export const FETCH_SELECTED_CATEGORY_SUCCESS = 'FETCH_SELECTED_CATEGORY_SUCCESS';

export const UPDATE_CATEGORY = 'UPDATE_CATEGORY';
export const UPDATE_CATEGORY_SUCCESS = 'UPDATE_CATEGORY_SUCCESS';

export const DELETE_SELECTED_CATEGORY = 'DELETE_SELECTED_CATEGORY';

